
CREATE TABLE GROUPS ( 
   GROUP_NAME VARCHAR(50) NOT NULL, 
   COURSE INT NOT NULL
);

INSERT INTO GROUPS VALUES ('12pv5',2); 
INSERT INTO GROUPS VALUES ('11pv5',1); 
INSERT INTO GROUPS VALUES ('10pv5',2); 